name: CI

on:
    push:
        branches:
            - master
            - alpha
            - beta
    pull_request:
        branches:
            - master
            - alpha
            - beta

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - run: npm install

            - name: Test Project Scaffolding & Build
              run: |
                  mkdir -p /tmp/test-ci-web
                  node bin/vertigis-web-sdk.js create /tmp/test-ci-web/sample-app --no-skills
                  cd /tmp/test-ci-web/sample-app
                  npm run build
                  test -f build/main.js

